# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    serializer: ~
    indexes:
        app: null
        
#        app:
#            settings:
#                index:
#                    analysis:
#                        analyzer: 
#                            default: 
#                                type: pattern
#            types:
#                user:
#                    serializer:
#                        groups: [elastica]
#                    persistence:
#                        driver: orm
#                        model: App\Entity\User
                        #elastica_to_model_transformer:
#                        provider:  
#                          query_builder_method: findAllQueryElastica
#                        listener: ~
#                        finder: ~ 
