twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
      - bootstrap_4_layout.html.twig
    globals:
      public_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    exception_controller: null

    #embeded css for emails
    paths:
      'public/css/emails': styles