services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    App\DataFixtures\UserFixtures: 
      public: true
    App\DataFixtures\WorkoutFixtures: 
      public: true
    App\DataFixtures\BodyweightActivityFixtures: 
      public: true
    App\DataFixtures\MovementActivityFixtures: 
      public: true
    App\DataFixtures\MovementSetActivityFixtures: 
      public: true
    App\DataFixtures\WeightActivityFixtures: 
      public: true
