parameters:
    uploads_dir_name: 'test_uploads'
    uploads_base_url: '%env(SITE_BASE_URL)%/%uploads_dir_name%'
    uploads_directory: '%kernel.project_dir%/public/%uploads_dir_name%'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    router.request_context.scheme: '%env(SITE_BASE_SCHEME)%'
    router.request_context.host: '%env(SITE_BASE_HOST)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    App\DataFixtures\UserFixtures: 
      public: true
    App\DataFixtures\WorkoutFixtures: 
      public: true
    App\DataFixtures\BodyweightActivityFixtures: 
      public: true
    App\DataFixtures\MovementActivityFixtures: 
      public: true
    App\DataFixtures\MovementSetActivityFixtures: 
      public: true
    App\DataFixtures\WeightActivityFixtures: 
      public: true
    App\DataFixtures\CuriosityFixtures: 
      public: true
